name: {{name.snakeCase()}}
description: {{description}}
version: 1.0.0+1
publish_to: none
environment: 
  sdk: '>3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  {{name.snakeCase()}}_domain:
    path: packages/domain
  {{name.snakeCase()}}_infrastructure:
    path: packages/infrastructure
  {{name.snakeCase()}}_application:
    path: packages/application
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.4
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.1
  readmore: ^2.2.0
  easy_date_timeline: ^1.0.3
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.0
  images_picker: ^1.2.11
  flutter_dotenv: ^5.1.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/env/development.env
  fonts: 
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
